# =========================
# Build stage
# =========================
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copy csproj and restore dependencies
COPY URLShortener/*.csproj ./URLShortener/
RUN dotnet restore ./URLShortener/URLShortener.csproj

# Copy the rest of the source code
COPY . .
WORKDIR /src/URLShortener

# Build the application
RUN dotnet publish -c Release -o /app/publish

# =========================
# Runtime stage
# =========================
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app

# Copy published output
COPY --from=build /app/publish .

# Expose HTTPS port
EXPOSE 443

# Run the app
ENTRYPOINT ["dotnet", "URLShortener.dll"]
